### ISSUE TITLE
Query list of supported distros

### ISSUE THREAD

**Issue by adamjstewart** [python-distro/distro#256]
We use `distro` in the [Spack package manager](https://spack.io/) to help us identify which Linux distro we are building software for. One feature we would like to add is something like `distro.supported_distros`, which would return the same list as contained in the [docs](https://distro.readthedocs.io/en/latest/#distro.id). See https://github.com/spack/spack/issues/14717 for more explanation as to why this feature would be useful.

**Comment by ferdnyc** [comment]
@adamjstewart The thing of it is, that list is not exhaustive. And in fact, it's not even comprehensive. Calling it the "supported" list would be a misrepresentation, because `distro` supports many more Linux distributions than just the ones listed there.

As the docs say, those are (some of) the distros where the identification is _stable_ — if it comes back with one of those values, you can rely on the OS being the indicated one. But there are many, many possible outputs beyond just the strings listed in that table.

(Both `manjaro` and `mandrake` are recognized, but not listed. Nor is Intel's Clear Linux, just as a random pick of one I noticed was missing. So, on a Clear system `distro.id()` will return... well, I have no idea, because there's no special-case code for it in the module. But it will return _something_ that's not on that list, most likely.)

`distro` _supports_ **ANY** Linux installation on a best-effort level, and even plenty of non-Linux installations. (There are even several BSD flavors on the stable-ID list.) The list of possible outputs from `distro.id()` is not finite, and (with its current design) never can be.

**Comment by sethmlarson** [comment]
Agree with @ferdnyc, as much as this would be a useful feature we'd be over-promising that OS distros don't break in the future. The only way to ensure this wouldn't happen would be testing every new version of a distro which isn't sustainable for this team as-is. I'm proposing we close this one?

**Comment by adamjstewart** [comment]
Sounds good, thanks for the clarification!
